[2025-02-08T08:26:55.150+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taxi_demand_prediction.scrape_flight_arrivals manual__2025-02-08T08:26:45.843525+00:00 [queued]>
[2025-02-08T08:26:55.204+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taxi_demand_prediction.scrape_flight_arrivals manual__2025-02-08T08:26:45.843525+00:00 [queued]>
[2025-02-08T08:26:55.210+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-02-08T08:26:55.375+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): scrape_flight_arrivals> on 2025-02-08 08:26:45.843525+00:00
[2025-02-08T08:26:55.388+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2025-02-08T08:26:55.425+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taxi_demand_prediction', 'scrape_flight_arrivals', 'manual__2025-02-08T08:26:45.843525+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/taxi_demand_pipeline.py', '--cfg-path', '/tmp/tmpbbpr_80g']
[2025-02-08T08:26:55.429+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask scrape_flight_arrivals
[2025-02-08T08:26:55.689+0000] {task_command.py:415} INFO - Running <TaskInstance: taxi_demand_prediction.scrape_flight_arrivals manual__2025-02-08T08:26:45.843525+00:00 [running]> on host 0ec2860535ef
[2025-02-08T08:26:56.099+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='taxi_demand_prediction' AIRFLOW_CTX_TASK_ID='scrape_flight_arrivals' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T08:26:45.843525+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T08:26:45.843525+00:00'
[2025-02-08T08:26:59.146+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/skp_scraper.py", line 12, in scrape_flights
    driver.get(SKP_URL)
NameError: name 'SKP_URL' is not defined
[2025-02-08T08:26:59.435+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=taxi_demand_prediction, task_id=scrape_flight_arrivals, execution_date=20250208T082645, start_date=20250208T082655, end_date=20250208T082659
[2025-02-08T08:26:59.918+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task scrape_flight_arrivals (name 'SKP_URL' is not defined; 216)
[2025-02-08T08:26:59.980+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-08T08:27:00.177+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
