[2025-02-07T22:19:23.691+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T22:19:23.719+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_price_etl.transform scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-02-07T22:19:23.737+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_price_etl.transform scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-02-07T22:19:23.739+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-02-07T22:19:23.865+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2025-01-11 00:00:00+00:00
[2025-02-07T22:19:23.877+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=692) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T22:19:23.880+0000] {standard_task_runner.py:72} INFO - Started process 704 to run task
[2025-02-07T22:19:23.881+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_price_etl', 'transform', 'scheduled__2025-01-11T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmpyw56de47']
[2025-02-07T22:19:23.886+0000] {standard_task_runner.py:105} INFO - Job 229: Subtask transform
[2025-02-07T22:19:23.968+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_price_etl.transform scheduled__2025-01-11T00:00:00+00:00 [running]> on host f4ec8002467d
[2025-02-07T22:19:24.132+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_price_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-11T00:00:00+00:00'
[2025-02-07T22:19:24.136+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T22:19:24.137+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T22:19:24.139+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2025-02-07 22:19:23.720741+00:00
[2025-02-07T22:19:24.140+0000] {logging_mixin.py:190} INFO - Dag name:crypto_price_etl and current dag run status:running
[2025-02-07T22:19:24.141+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T22:19:24.173+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crypto_dag.py", line 63, in transform_task
    df = transform_data(data)
         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crypto_dag.py", line 40, in transform_data
    df = df[['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume']]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume'], dtype='object')] are in the [columns]"
[2025-02-07T22:19:24.202+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-07T22:19:24.203+0000] {logging_mixin.py:190} INFO - Task start:2025-02-07 22:19:23.720741+00:00 end:2025-02-07 22:19:24.201239+00:00 duration:0.480498
[2025-02-07T22:19:24.204+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: crypto_price_etl> dagrun:<DagRun crypto_price_etl @ 2025-01-11 00:00:00+00:00: scheduled__2025-01-11T00:00:00+00:00, state:running, queued_at: 2025-02-07 22:14:05.755938+00:00. externally triggered: False>
[2025-02-07T22:19:24.205+0000] {logging_mixin.py:190} INFO - Failure caused by "None of [Index(['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume'], dtype='object')] are in the [columns]"
[2025-02-07T22:19:24.206+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=crypto_price_etl, task_id=transform, run_id=scheduled__2025-01-11T00:00:00+00:00, execution_date=20250111T000000, start_date=20250207T221923, end_date=20250207T221924
[2025-02-07T22:19:24.227+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T22:19:24.231+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 229 for task transform ("None of [Index(['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume'], dtype='object')] are in the [columns]"; 704)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crypto_dag.py", line 63, in transform_task
    df = transform_data(data)
         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crypto_dag.py", line 40, in transform_data
    df = df[['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume']]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume'], dtype='object')] are in the [columns]"
[2025-02-07T22:19:24.263+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T22:19:24.303+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T22:19:24.312+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
