[2024-11-23T09:18:12.788+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T09:18:12.825+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_json_dag.start scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T09:18:12.845+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_json_dag.start scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T09:18:12.846+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-23T09:18:12.877+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): start> on 2024-11-22 00:00:00+00:00
[2024-11-23T09:18:12.887+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T09:18:12.892+0000] {standard_task_runner.py:72} INFO - Started process 72 to run task
[2024-11-23T09:18:12.892+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_json_dag', 'start', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/extract_json.py', '--cfg-path', '/tmp/tmphl5mzz_4']
[2024-11-23T09:18:12.898+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask start
[2024-11-23T09:18:13.005+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_json_dag.start scheduled__2024-11-22T00:00:00+00:00 [running]> on host f4ec8002467d
[2024-11-23T09:18:13.213+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_json_dag' AIRFLOW_CTX_TASK_ID='start' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T09:18:13.215+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T09:18:13.216+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T09:18:13.217+0000] {logging_mixin.py:190} INFO - Current task name:start state:running start_date:2024-11-23 09:18:12.826182+00:00
[2024-11-23T09:18:13.218+0000] {logging_mixin.py:190} INFO - Dag name:extract_json_dag and current dag run status:running
[2024-11-23T09:18:13.219+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T09:18:13.222+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_json.py", line 8, in extract_from_json
    with open("/data/data.json", "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data.json'
[2024-11-23T09:18:13.246+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-23T09:18:13.247+0000] {logging_mixin.py:190} INFO - Task start:2024-11-23 09:18:12.826182+00:00 end:2024-11-23 09:18:13.245807+00:00 duration:0.419625
[2024-11-23T09:18:13.248+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): start> dag:<DAG: extract_json_dag> dagrun:<DagRun extract_json_dag @ 2024-11-22 00:00:00+00:00: scheduled__2024-11-22T00:00:00+00:00, state:running, queued_at: 2024-11-23 09:18:06.612934+00:00. externally triggered: False>
[2024-11-23T09:18:13.249+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/data/data.json'
[2024-11-23T09:18:13.250+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_json_dag, task_id=start, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T091812, end_date=20241123T091813
[2024-11-23T09:18:13.277+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T09:18:13.278+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task start ([Errno 2] No such file or directory: '/data/data.json'; 72)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_json.py", line 8, in extract_from_json
    with open("/data/data.json", "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data.json'
[2024-11-23T09:18:13.316+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T09:18:13.349+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T09:18:13.353+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
